nome = str(input("Digite seu nome: ")).strip()
print("Analisando seu nome...")
print(f"Seu nome tem {nome.upper()} letras maiúsculas")
print(f"Seu nome tem {nome.lower()} letras minúsculas")
print(f"Seu nome tem {nome.__len__() - nome.count(' ')} letras")
print(f"Seu primeiro nome tem {nome.find(' ')} letras")