# AUTOMAÇÃO PARA ABRIR O SISTEMA SÊNIOR
import pyautogui

pyautogui.alert('Por favor, não mexa nos teclados nem no mouse até o fim do processo.')
pyautogui.press('winleft')
pyautogui.sleep(2)
pyautogui.write('chrome')
pyautogui.sleep(3)
pyautogui.press('enter')
pyautogui.sleep(2)
pyautogui.write('http://infraprd.seniorcloud.com.br:8080/siltwms/#tarefasprincipais')
pyautogui.sleep(2)
pyautogui.press('enter')
pyautogui.sleep(6)
pyautogui.write('erick.franca')
pyautogui.sleep(1)
pyautogui.press('tab')
pyautogui.sleep(1)
pyautogui.write('Erick1806')
pyautogui.sleep(1)
pyautogui.press('tab')
pyautogui.sleep(1)
pyautogui.press('down')
pyautogui.sleep(1)
pyautogui.press('down')
pyautogui.sleep(1)
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.press('enter')
pyautogui.sleep(3)
pyautogui.moveTo(12, 221)
pyautogui.sleep(1)
pyautogui.click()
pyautogui.sleep(1)
pyautogui.moveTo(82, 264)
pyautogui.sleep(1)
pyautogui.click(clicks=2)
pyautogui.sleep(1)
pyautogui.moveTo(144, 305)
pyautogui.click()
pyautogui.sleep(3)
pyautogui.press("enter")
pyautogui.sleep(1)
pyautogui.moveTo(506, 560)
pyautogui.sleep(3)
pyautogui.click()
pyautogui.sleep(2)
pyautogui.moveTo(618, 347)
pyautogui.sleep(1)
pyautogui.doubleClick()
pyautogui.sleep(2)
pyautogui.moveTo(380, 656)
pyautogui.click()
pyautogui.sleep(2)
pyautogui.moveTo(462, 509)
pyautogui.click()