import pyautogui
pyautogui.press('winleft')
pyautogui.sleep(1)
pyautogui.write('Chrome')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(3)
pyautogui.write('https://fecaf.brightspace.com/d2l/loginh/')
pyautogui.press('enter')
pyautogui.sleep(4)
pyautogui.moveTo(617, 407)
pyautogui.sleep(2)
pyautogui.click()
pyautogui.sleep(2)
pyautogui.write('43963')
pyautogui.sleep(1)
pyautogui.press('tab')
pyautogui.sleep(1)
pyautogui.write('18061999')
pyautogui.sleep(1)
pyautogui.press('tab')
pyautogui.sleep(1)
pyautogui.press('enter')